# Generated by Django 6.0.6 on 2026-06-23 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='date of entry, must be the day of logging')),
                ('unit_calories', models.PositiveIntegerField(help_text='Calories per unit food')),
                ('amount', models.FloatField(help_text='Number of unit food consumed')),
            ],
        ),
        migrations.CreateModel(
            name='water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.PositiveIntegerField(help_text='water drinked in mL')),
            ],
        ),
        migrations.CreateModel(
            name='medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency_type', models.CharField(choices=[('daily', 'Every day'), ('weekly', 'Specific days')], max_length=10)),
                ('days', models.ManyToManyField(blank=True, to='tracker.day')),
            ],
        ),
    ]
