# Generated by Django 6.0.6 on 2026-06-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(help_text='Name of food', max_length=30, null=True),
        ),
    ]
