# Generated by Django 6.0.6 on 2026-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_medication_days_delete_day_medication_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='unit_calories',
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(default=123, help_text='Calories of food'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='days',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency_type',
            field=models.CharField(max_length=10),
        ),
    ]
