# Generated by Django 6.0.6 on 2026-06-26 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_food_amount_remove_food_unit_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='time',
            field=models.TimeField(default=datetime.time(23, 10, 36, 813110)),
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(default=datetime.date(2026, 6, 26), help_text='date of entry, must be the day of logging'),
        ),
        migrations.AlterField(
            model_name='water',
            name='date',
            field=models.DateField(default=datetime.date(2026, 6, 26)),
        ),
    ]
