# Generated by Django 6.0.6 on 2026-06-26 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_water_time_alter_food_date_alter_water_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='name',
            field=models.CharField(default='Water intake', max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='date of entry, must be the day of logging'),
        ),
        migrations.AlterField(
            model_name='water',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='water',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
